import { FeatureFlagProvider } from "@/src/components/feature-flag";
import flagsmith from "flagsmith/isomorphic";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await flagsmith.init({
    environmentID: process.env.FLAGSMITH_ENVIRONMENT_ID,
    api: process.env.FLAGSMITH_API,
  });

  const serverState = flagsmith.getState();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FeatureFlagProvider serverState={serverState}>
          {children}
        </FeatureFlagProvider>
      </body>
    </html>
  );
}
